【WIP】feature/202011/add_attribute
ochibi1/MyTodo pull request #10
Opened 2020-11-26 05:50 UTC by ochibi1

##What
taskNumber(Int型)のattributeを追加。
新規追加項目画面に、該当の入力欄を追加。model内にvalidateのメソッドを追加予定。

##Why
テストコード実装に必要な項目を増やすため。

2020-11-26 06:03 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +        guard let taskPriority = self.numberField.text,
`self.numberField.text.toInt()`
`self.numberField.text as Int!`

これでいけないかと思ったんですが、だめでした。。

2020-11-26 06:16 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +        guard let taskPriority = self.numberField.text,
必要なチェックも行わないとね。
・数字とみなせる文字なのか。（文字列の数字チェック）

あとは「swift string int 変換」とかで検索してみたら？

2020-11-26 07:14 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +        guard let taskPriority = Int(self.numberField.text!)!,
toInt()はSwift2.0以降、廃止されていることを知りまして、Int()でキャストできるという記事を見つけたので、このように記述してみているんですが、`Initializer for conditional binding must have Optional type, not 'Int'`と、エラーが出ています。オプショナルだと空データでもOKになってしまうので、`!`を付けているんですが、、他のやり方がないかと調べてみているんですが、まだ模索中です。。

2020-11-26 07:14 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +              !taskPriority = nil else {
isEmptyはStringのプロパティに使えるものだということを学んだので、他の書き方が必要だと思ったんですが、調べ方が下手くそでまだ見つけられず、ここの行は一旦変える必要がある、と認識させるためにエラーにさせたままにしています。。

2020-11-28 05:34 UTC, ochibi1 commented on MyTodo/Model/Task+CoreDataClass.swift
> +    func isNumberValid(_ taskNumber: String) -> Bool {
attirbuteとしてのtaskNumberの型は Int16にしているけれど、空データかどうか確認するためのisEmptyを使いたかったので、String型にしました。Int16型として判定したいときは、キャストを使っているんですが、こういう考え方で進めてよかったんでしょうか？

2020-11-28 05:34 UTC, ochibi1 commented on MyTodo/Model/Task+CoreDataClass.swift
> +        //16進数の文字列ではないか（これについては、どうやって正規表現とか使うのかイメージ湧いていない）
ここのコメントアウト部分に関しては、今書き直しているところです。

2020-11-28 06:07 UTC, ryudrag commented on MyTodo/Model/Task+CoreDataClass.swift
> +    func isNumberValid(_ taskNumber: String) -> Bool {
「入力値（テキストフィールドの値）が数値型のカラムに入れられるかのチェック関数」と言う意味では良いんじゃない？

2020-11-28 06:25 UTC, ochibi1 commented on MyTodo/Model/Task+CoreDataClass.swift
> +    func isNumberValid(_ taskNumber: String) -> Bool {
なるほど。その観点で考えたらstring型にしておく必要性がありますね。
回答、有難うございます！

2020-11-30 03:37 UTC, ryudrag commented
autolayoutで左右からの距離だけを気にしていると、画面サイズ次第ではこんなことになる。
<Img src="https://user-images.githubusercontent.com/12134860/100566192-b71fc680-3308-11eb-8046-d9c2a1bce601.png" width=200>

2020-11-30 03:43 UTC, ryudrag requested changes
指摘しましたー

2020-11-30 03:43 UTC, ryudrag commented on MyTodo/ContentViewCell.swift
> +        numberLabel.numberOfLines = 0
桁数考えると、複数行になることはないんじゃない？要は指定不要ではってこと。

2020-11-30 03:43 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +
整形するためとか意図がなければ不要な変更はしないでね。

2020-11-30 03:43 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +        data.taskNumber = Int16(taskPriority)
taskPriorityは上のguard節で既にInt16になってる。

2020-11-30 03:43 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +extension String {
これはなんのための拡張？

2020-11-30 03:43 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +    func isAlphanumeric() -> Bool {
数字の判定なら isNumeric だね。

2020-11-30 03:43 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +        return self.range(of: "[^0-9]+", options: .regularExpression) == nil && self != ""
空文字を判定するのが先だね。（簡単な判定を先に）

2020-11-30 03:43 UTC, ryudrag commented on MyTodo/Model/Task+CoreDataClass.swift
> +    func isNumberValid(taskNumber: String?) -> Bool {
これを使っている箇所がないんじゃない？

2020-11-30 03:58 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +
2行開けた方が見やすくなるなと思って付け足していました。。
開けない方がよかったでしょうか？

2020-11-30 03:59 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +extension String {
消し忘れです・・・すみません。ご指摘有難うございます。

2020-11-30 04:28 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +
間を開けるのは1行のみで良いよ。

2020-11-30 04:29 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +
承知です！ご指摘有難うございます！

2020-11-30 08:28 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +        Task.isNumberValid(taskNumber: self.numberField.text)
ここで、self.numberField.textを引数として、「Taskとして代入して良いデータか、のチェック」ができるようになったと思うんですが、返り値について質問させてください。

ここのメソッドで、もし代入できない、と判断したらfalseが返されると思うんですが、この記述のままだと返り値を使っていないことになると思うんです。そこについては理解合ってるでしょうか？
（さっきの理解が合ってる前提での話なんですが、）falseだった場合にエラーダイアログが表示されるようにするには、70行目に戻す必要がある・・・という考えは間違っているでしょうか？

2020-11-30 08:30 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +        Task.isNumberValid(taskNumber: self.numberField.text)
両方あってる。返り値を使ってfalseならエラー表示する必要あり。

2020-11-30 08:58 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +        guard let taskPriority = self.numberField.text,
```
if !Task.isNumberValid(taskNumber: self.numberField.text) {
    //アラート
}
```

で良いんじゃない？Task.isNumberValidの中でnilチェックもやってるし。

2020-11-30 09:31 UTC, ryudrag commented on MyTodo/ContentViewCell.swift
> +    let numberLabel: UILabel = {
ここはもう `let numberLabel = UILabel()` で良いね。

2020-11-30 09:38 UTC, ryudrag requested changes
あと、端末によって保存ボタンが潰れるのが直ってないよね？

2020-11-30 09:38 UTC, ryudrag commented on MyTodo/DataController.swift
> +        container.persistentStoreDescriptions = [description]
`self.` ねー。

2020-11-30 09:38 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +    let numberField: UITextField! = UITextField(frame: .zero)
すっごい今更なんだけど、`let` の時点で `: UITextField!` の ! は要らないね。上の行も含め。
さらに言うと、右辺が `UITextField(frame: .zero)` の時点で `: UITextField!` の型指定自体が不要。

2020-11-30 09:38 UTC, ryudrag commented on MyTodo/Model/entity/TaskStore.xcdatamodeld/TaskStore.xcdatamodel/contents
> +        <attribute name="taskNumber" optional="YES" attributeType="Integer 16" defaultValueString="0" usesScalarValueType="YES"/>
初版のxcdatamodelではこのattributeは消しておかないと。

2020-11-30 09:47 UTC, ochibi1 commented on MyTodo/DataController.swift
> +        container.persistentStoreDescriptions = [description]
25行目だけ、で間違いないでしょうか？
（23, 24行目は付け足すとエラーになりました）

2020-11-30 12:45 UTC, ryudrag requested changes
ボタンが潰れる件は同じように対応したところを見直して。

2020-11-30 12:45 UTC, ryudrag commented on MyTodo/DetailViewController.swift
> +            make.left.equalTo(self.label.snp.left).offset(70.0)
このautolayoutの制約だと、左だけ固定で右は可変という不恰好になるよ。
幅を固定したまま、親のx軸の真ん中と言う制約があるから探してみて。

2020-11-30 12:45 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +            make.left.equalTo(self.numberField.snp.left).offset(70.0)
上の方に書いたやつと一緒

2020-11-30 12:45 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +        data.taskNumber = Int16(self.numberField.text!)!
あれ、ここ指摘しなかったっけ？

2020-11-30 13:05 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +        data.taskNumber = Int16(self.numberField.text!)!
以前指摘いただいた時は、taskPriorityをguard節でInt16型に指定してたんですけど、70行目の記述を変えて、Int16型の指定が無くなったので、キャスト必要だと思って書き直しました。

2020-11-30 13:08 UTC, ryudrag commented on MyTodo/DataController.swift
> +        container.persistentStoreDescriptions = [description]
そうそう。上はローカルだからいらない。

2020-11-30 13:12 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +        data.taskNumber = Int16(self.numberField.text!)!
消えてた…消したかな…まぁこれで良いや…

2020-11-30 13:14 UTC, ryudrag approved these changes

2020-11-30 13:18 UTC, merged