Feature/202010/main screen view
ochibi1/MyTodo pull request #3
Opened 2020-10-29 09:18 UTC by ochibi1

##What
SwiftUI, Combineフレームワークを使用して、メイン画面を作成。
ナビゲーションバーと別ブランチで作成予定の項目追加画面で入力された値が表示される想定でのリストを作成した。

##Why
Todoアプリに必須の実装であるため。

2020-10-29 10:00 UTC, ryudrag commented on MyTodo/ContentView.swift
>  import SwiftUI
ごめん、最初に指摘するべきだった。
SwiftUIはGUIでの画面作成の認識でコードベースではない…

2020-10-29 10:01 UTC, ryudrag requested changes
指摘しました。

2020-10-29 10:34 UTC, ochibi1 commented on MyTodo/ContentView.swift
>  import SwiftUI
学習不足でした。。すみません。
storyboardとSwiftUIの差異が正しく理解できていなかったようです。
（こちらの記事で、最終的に判断してしまいました
https://www.punkrockseblog.tokyo/2020/0808/music-purchased-soundsource-no2-200808.html）

コードベースでのUI作成、自体が認識正しくできていないようなので、内容の更新に少し時間がかかってしまうと思います。。

2020-10-29 11:08 UTC, ryudrag commented on MyTodo/ContentView.swift
>  import SwiftUI
SwiftUIがGUIと言うのも言い過ぎかな…

SwiftUiは個人アプリやシンプルアプリだといいけど、
大規模複雑アプリだとまだ採用はないかなー。
ios13以降しか対応してないのも致命的。
コアな実装もできないし…

2020-11-02 06:12 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
ビルドすると、"Argument passed to call that takes no arguments" というエラーが出るので調べていますが、引数が無い、と言われている意味がよく分かっておりません。。
教えてもらえると嬉しいです。

2020-11-02 06:17 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
`UIViewController` には `rootView` を引数とするイニシャライザはないねー。
`ContentViewController()` これで十分。

2020-11-02 06:28 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
2b198fcでのプッシュ内容でビルドすると、以下のコメントがデバッグ欄に表示されます。

Warning: Error creating LLDB target at path '/Users/laflora/Library/Developer/Xcode/DerivedData/MyTodo-aofzhmdnpbisiwalsgmqaxruhaei/Build/Products/Debug-iphonesimulator/MyTodo.app'- using an empty LLDB target which can cause slow memory reads from remote devices.

シミュレーターではビルドは成功するのですが、アプリがすぐクラッシュしてしまうことを確認しました。
これは、どの部分が悪さをしているのか検討がついておりません。
ヒントになる部分を指摘いただけると嬉しいです。よろしくお願いします。

2020-11-02 06:37 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
clean build folderしても同じ？？
ネットでも質問している人はいるけど解決したという書き込みはないねぇ…

2020-11-02 06:42 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
clean build folderは、.xcworkspaceの方で実施で合ってますか？？

2020-11-02 06:45 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
そうそう

2020-11-02 06:47 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
Snapkitのフレームワークが見つからない、とのエラーが表示されるようになりました。

2020-11-02 06:48 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
んじゃあもういっかい
pod install
してみてー。

2020-11-02 07:01 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
https://stackoverflow.com/questions/40358719/framework-not-found-googletoolboxformac
https://qiita.com/yoshoo/items/4d74325bb6f05ba2b456

こちら1つ目の記事に書いてある設定は済んでいるので、2つ目の記事の”追記”の部分を真似てやってみようと思うんですが、「podsディレクトリ、xcworkspaceファイル、（pods.lockは自動生成されるはずなので大丈夫かと思う）の削除」をするのは、綺麗なファイルを作り直す、という意味でやるんでしょうか？

2020-11-02 07:16 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
uninstall cocoapodsする前に、podfileも消した方がベターでしょうか？

2020-11-02 07:36 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
いや、uninstall cocoapodsはやらない。
pod install
のコマンド打つだけー。

2020-11-02 07:38 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
うわ。。すいません。
uninstall してinstallし直してpod installしたところでした。

2020-11-02 07:39 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
ビルド時のエラーは変わらず同じだったんですが、cocoapodsインストールし直したのまずかったでしょうか？

2020-11-02 07:52 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
いや、そこは関係無いはず。
xcworkspaceで開いてるよね？

2020-11-02 07:53 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
よかった・・・・

はい！xcworkspaceで開いてます。

2020-11-02 07:55 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
んじゃ追記部分をやってみよう。
`podsディレクトリ、xcworkspaceファイル、（pods.lockは自動生成されるはずなので大丈夫かと思う）の削除`
は rm -rf ●●●●で削除ね。

2020-11-02 07:56 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
はい！やってみます！返信、感謝です。有難うございます。

2020-11-02 08:08 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = ContentViewController(rootView: ContentView)
開いていたXcode全て閉じる
rm -rf　コマンドで、3つのファイル削除
pod install 
MyTodo.xcworkspaceを開く
ビルド

でやってみましたが、変化なかったので、もう一度clean build folderもし直してみました。
エラー内容が変わりませんでした。
podfile : https://gyazo.com/5a28073ff4667745dc35c630c39b83c0
Xcodeのエラー画面：https://gyazo.com/0480b89bc148012295b017b3d48b1502

2020-11-02 08:16 UTC, ryudrag commented
こっちで試そうと思ったら
Podfile
がないね。コミットしてちょーだい。

2020-11-02 08:19 UTC, ochibi1 commented
> こっちで試そうと思ったら
> Podfile
> がないね。コミットしてちょーだい。

ご確認よろしくお願いします🙇‍♀️

2020-11-02 08:53 UTC, ryudrag commented
こっちでやったら
https://qiita.com/nakamurau1@github/items/e4a810e21e626cf6f09a
の一番だけで行けたけどねぇ…

2020-11-02 08:59 UTC, ochibi1 commented
試してみて頂いて有難うございました。

なんでだろう・・・・同じように設定しているはずなのですが・・・。
xcproject と .xcworkspaceの両方で設定しているのがまずいですかね？
https://gyazo.com/b092fe0a4ca33c0b1fa4f5c8109a3f01

2020-11-02 09:02 UTC, ryudrag commented
一旦、今修正している途中をcommit＆pushして今のフォルダをリネーム。
もう一度ここからクローンしてきてみたら？
俺はクローンと

```
こっちでやったら
https://qiita.com/nakamurau1@github/items/e4a810e21e626cf6f09a
の一番だけで行けたけどねぇ…
```

だけで行けたし。

2020-11-02 09:04 UTC, ochibi1 commented
フォルダのリネームは、MyTodoフォルダのことで合ってますか？？

2020-11-02 09:05 UTC, ryudrag commented
そうそう。
.gitフォルダが入っているフォルダ

2020-11-02 09:07 UTC, ochibi1 commented
やってみます！
フォルダ名変えた後は、クローンしたもののローカルリポジトリ をまた作る感じですかね？？

2020-11-02 09:08 UTC, ryudrag commented
クローンしたものはリポジトリあるよー。

2020-11-02 09:12 UTC, ochibi1 commented
なるほど。有難うございます！

リネーム、コマンドでやろうと思うのですが、mv ではなく、renameの方が良いですかね？？

2020-11-02 09:38 UTC, ochibi1 commented
今、このブランチの内容をクローンして再ビルドしてみたのですが、結果が変わらなかったです。

松本さんにクローンして頂いたのは、同じものだったでしょうか？？

2020-11-04 08:20 UTC, ochibi1 commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = UITableViewController()
ここをUITableViewControllerにすることで、ビルドが通って以下のリストが表示されるようになりました。
https://gyazo.com/6f367f664d3485b1c642d220da12b997

ですが、ContentViewの中身は全く関係ないものになっているので、そもそも色んな前提が抜けていると思うので、ご指摘いただきたいです。。よろしくお願いします。

2020-11-04 09:08 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = UITableViewController()
1. ContentViewControllerクラスの継承元を `UIViewController` から `UITableViewController` に変更
2. ここでインスタンス化するクラスを `ContentViewController` に変更

2020-11-04 09:09 UTC, ryudrag commented on MyTodo/ContentView.swift
> +    let table: UITableView = UITableView(frame: CGRect(x: 50, y: 50 , width: 200, height: 500))
このクラス自体がUITableViewなのにここでUITableViewをさらにインスタンス化する意図とは？

2020-11-04 09:13 UTC, ryudrag commented on MyTodo/ContentView.swift
> +    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
これはUITableViewDelegateの実装になるのでここでは不要。
したがってこのビューでやることはない＝このクラスは不要。

2020-11-04 09:14 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = UITableViewController()
やっぱちょい待ち

2020-11-04 09:16 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> +            window.rootViewController = UITableViewController()
上は取り消し。
ここは `ContentViewController` をインスタンス化するように変更。

2020-11-04 09:17 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +        override func viewDidLoad() {
このメソッド内で行なっている処理は本来initでやるべきこと。
なのでviewDidLoadからinitに変更。

2020-11-04 09:17 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +            super.didReceiveMemoryWarning()
superのメソッド呼ぶしか処理を行わないならオーバーライドは不要。
よってこのメソッドは不要。

2020-11-04 09:19 UTC, ryudrag commented on MyTodo/SnapKit-Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
このファイルはここにあるべきではない。
Podsのどこかにあるでしょ？？
このファイルは削除で。

2020-11-04 09:20 UTC, ryudrag commented on MyTodo/TableViewController.swift
> +//
現状の作りだとこのファイルは不要なので削除。

2020-11-04 09:20 UTC, ryudrag requested changes
指摘完了。

2020-11-05 03:50 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +            table.register(UITableViewCell.self, forCellReuseIdentifier: "data")
ここの `UITableViewCell.self` を自作のセルに置き換える。

2020-11-05 03:51 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +            let cell = tableView.dequeueReusableCell(withIdentifier: "myCell", for: indexPath)
上の23行目で記述されたidentifierとwithIdentifierが一致していない。

2020-11-07 13:12 UTC, ryudrag commented on MyTodo/ContentViewCell.swift
> +            make.left.right.equalTo(60.0).inset(10)
こんな指定の仕方は普通しないねー…
右と左をいちいち別々に計算しないと、
実際になんの値にしようとしてるのか分かんないから。

2020-11-07 13:16 UTC, ryudrag commented on MyTodo/ContentViewCell.swift
> +            make.left.equalTo(10)
左のマージンをcontentViewで調整する必要あるの？
結果としてラベルが、画面の左からどの位置に来るかは計算済み？
今後の機能追加で左ぴったりに何かを表示したい場合、
わざわざここを弄る必要が出てくるよ。

2020-11-07 13:17 UTC, ryudrag commented on MyTodo/TableViewCell.swift
> +//  TableViewCell.swift
このクラスを作った（残してる）意図とは？

2020-11-08 01:47 UTC, ochibi1 commented on MyTodo/TableViewCell.swift
> +//  TableViewCell.swift
消し忘れていました。ご指摘有難うございます！

2020-11-08 02:27 UTC, ochibi1 commented on MyTodo/ContentViewCell.swift
> +            make.left.equalTo(10)
セルの区切りの線（UITableViewCellSeparatorView）が、contentViewCellのの中に含まれていると思っていて、その線が端っこから少し離れて始まっている方が見た目がよさそうだと考えてmargin設定していました。
▶︎だとしても、contentViewで設定するものではなかった。（なぜなら、そもそも、contentViewと区切り線の階層位置が違っていたからcontentViewで設定しても反映されない）
今見直している途中で、区切り線とcontentViewCellが同率位置に配置されていて、（contentViewはTableViewCellContentViewの中にあるものだから、階層関係が）そもそもTableViewCellContentViewで余白を設定することと、区切りの線の開始・終了位置が関係ないもの、だと気付きました。

ラベルの開始位置は、そのマージン➕ ラベルのConstraintsで設定していたものになっていましたが、.left.rightでまとめてしまっていたため、insetの10が効いた部分から表示されいたことに気付きました。。

2020-11-08 04:23 UTC, ryudrag approved these changes

2020-11-08 11:58 UTC, merged