Feature/202011/navi bar
ochibi1/MyTodo pull request #4
Opened 2020-11-09 11:03 UTC by ochibi1

##What
UINavigationControllerで、contentViewControllerを初期画面として表示する設定で最上部のナビゲーションバーを作成。遷移先は本ブランチではコントローラー(addItemViewController)のみ作成。

##Why
画面遷移に必要な機能だから。

2020-11-09 11:05 UTC, ochibi1 commented on MyTodo/ContentViewController.swift
> +        addBtn = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: Selector(("onClick")))
ここのonClickが上手く作動していない気がしています。
ビルドは通るのですが、画面が表示されなくなっている理由がここの部分な気がするのですが、どう違うのか分かりかねたので、ご指摘など頂けると有り難いです。宜しくお願いします。

2020-11-09 12:53 UTC, ryudrag requested changes
コメントしましたー

2020-11-09 12:53 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
>              let window = UIWindow(windowScene: windowScene)
ここも変数を使わないようにしようか。

2020-11-09 12:53 UTC, ryudrag commented on MyTodo/SceneDelegate.swift
> -            self.window = window
画面が出ない理由はここじゃない？

2020-11-09 12:53 UTC, ryudrag commented on MyTodo/addItemViewController.swift
> +//  ViewController.swift
間違ってる。コメントも大事だからね。

2020-11-09 12:53 UTC, ryudrag commented on MyTodo/addItemViewController.swift
> +class addItemViewController: UIViewController {
クラス名の頭が小文字はダメ。ファイル名も合わせて。

2020-11-09 12:53 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +        self.navigationItem.rightBarButtonItem = addBtn
これでビルド通った？左辺の型を良くみてみて。

2020-11-09 12:53 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +        addBtn = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: Selector(("onClick")))
変更して動かないなら、変更前に少しずつ戻していってどこの変更が原因か探ってね。せっかくビルドに時間がかからないんだから、こまめにビルドして確認した方が良いよ。現場では20分とかかかる時もあるからめんどいけど。

2020-11-09 12:57 UTC, ryudrag commented on MyTodo/addItemViewController.swift
> +class addItemViewController: UIViewController {
付け加え。頭が動詞は基本的にメソッド名だから、ItemAddViewとかがいいかも

2020-11-10 01:32 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +        self.navigationItem.rightBarButtonItem = addBtn
あー通るのか。rightBarButtonItemsの方しか使わないから気づかなかった。
まーとりあえずこれで良いや。

2020-11-10 01:33 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +        self.navigationItem.rightBarButtonItem = addBtn
そして例によってこのままだと変数はいらないね。

2020-11-10 02:25 UTC, ryudrag requested changes

2020-11-10 02:25 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +        self.title = "新規項目追加画面"
ここもinitで。
最初から決まっている値の設定は、なるべくinitでやるようにしてね。
その初期値をもとに親クラスがレイアウトしたりするパターンもあるから。
appearじゃないからまだマシだけど…

2020-11-10 02:25 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +        let second = ItemAddViewController()
ここも変数にする意味がないから無くそうか。

2020-11-10 02:25 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +        let second = ItemAddViewController()
まあ、あくまでも「現状は意味がない」だけど…

2020-11-10 02:40 UTC, ryudrag approved these changes

2020-11-10 02:51 UTC, merged