【WIP】Feature/202011/add screen view
ochibi1/MyTodo pull request #5
Opened 2020-11-11 06:23 UTC by ochibi1

##What
メイン画面から、ナビゲーションバーのボタン操作による遷移先画面のビュー作成。
CoreDataを使用して、遷移元の画面に入力データを受け渡せるよう実装中。

##Why
Todoアプリの仕様上必要な機能であるため。

2020-11-11 06:36 UTC, ryudrag requested changes
とりあえず一部だけ。

2020-11-11 06:36 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +            make.right.equalToSuperview().inset(40.0)
rightだけであればequalTo(-40)の方で。
この書き方はright.left.みたいに同時に指定する時。

2020-11-11 06:36 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +        saveBtn.snp.makeConstraints { make in
んー…これだとcgrectでの指定とあんまり変わらないね。autolayoutとしても活かせてない。一番最初の要素（基準）を指定する時だといいんだけど、それ以降は前の要素を基準にするのが普通かな。

2020-11-11 08:28 UTC, ochibi1 commented on MyTodo/ContentViewController.swift
> +    static let dataController = NSObject.shared.delegate as! DataController
app.delegateに指定したら、アプリ起動時に作られるから良いのかな、と思ったんですが、"DataControllerがスコープにない"とエラーが出たので、シーン作成で呼ばれるここの部分に指定できるかも、と思って記述しました。
が、エラー内容変わらないので、ファイル(Task+CoreData...達)の位置が違うからなのか・・・？と悩んでいます。

2020-11-11 08:28 UTC, ochibi1 commented on MyTodo/ContentViewController.swift
> +        self.table.reloadData()
イニシャライザ内で使ったtableを、スコープの範囲が違うので、ここで使えないのは理解できるんですが、ここで再度table定義してしまうと、データを更新する時に一緒に白紙状態に戻してしまうと思うので、どうやるのか考えていますが、もしヒントが頂けるなら・・・と思いpushしてます。

2020-11-11 08:28 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +    let saveBtn = UIButton(frame: .zero)
イニシャライザの中ではなく、クラスの中に置いたら、どちらも使えるようになるのでは・・・と思いましたが、意味がありませんでした。34行目以降の数値は、inputFieldを基準とした時のsaveBtnの位置を想定した数値で入れてみています。

2020-11-11 08:31 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +    static let dataController = NSObject.shared.delegate as! DataController
ここに作ったら結局appdelegateを取得しないといけないから意味ないねー

2020-11-13 00:23 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +    let saveBtn = UIButton(frame: .zero)
サンプルで修正しているけど、一応コメント。
プロパティとしておくのはオッケー。34行目の指定の仕方が間違ってる。
おそらく、設定したいviewと基準となるviewという考えなんだろうけど、使い方が違うね。
わからなかったらサンプル参照。

2020-11-13 00:29 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +    let saveBtn = UIButton(frame: .zero)
コメント、ご丁寧に有難うございます！
先ほど、サンプル参考に見直していたら、自分の間違いに気付きました。
「saveBtnの位置決める」と記述してる{}の外の部分で「inputFieldのsaveBtnの位置・・・」みたいなことになっていた▶︎基準値を置くのは、あくまで「何を基準として、どのくらいずらすのか」を記述する、{}内でのお話、ということだと理解しております。

2020-11-16 04:39 UTC, ryudrag commented on MyTodo.xcodeproj/project.pbxproj
> +				0F3BF6AD2553FB75007628D4 /* ContentViewCell.swift */,
これ昇順だったのが入れ替わってる。

2020-11-16 04:40 UTC, ryudrag commented on MyTodo/AppDelegate.swift
> +import CoreData
ここでこのimport要る？

2020-11-16 04:44 UTC, ryudrag commented on MyTodo/ContentViewController.swift
> +import CoreData
ここでこれ要る？

2020-11-16 04:46 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +import CoreData
ここでこれ要る？

2020-11-16 04:49 UTC, ochibi1 commented on MyTodo/AppDelegate.swift
> +import CoreData
消し忘れてました！ご指摘有難うございます！

2020-11-16 04:49 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +                self.dismiss(animated: true, completion: nil)
クロージャの中でselfとかメモリリークになるかもしれないから気をつけて。
selfのdismissって一覧に戻るの？

2020-11-16 04:49 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +                self.dismiss(animated: true, completion: nil)
同上

2020-11-16 04:50 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +    required init?(coder: NSCoder) {
下に追いやるのではなく、initの近くに置いておいて。

2020-11-16 04:51 UTC, ryudrag requested changes
コメントしました。

2020-11-16 04:55 UTC, ochibi1 commented on MyTodo.xcodeproj/project.pbxproj
> +				0F3BF6AD2553FB75007628D4 /* ContentViewCell.swift */,
どの作業で入れ替えてしまったのか忘れたんですが、ここは戻さないとだめなんでしょうか？（戻すとしたら・・・Xcode上でソートするのかな？と考えています）

2020-11-16 04:55 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +import CoreData
CoreDataは消し忘れてましたが、SnapKitはautolayout使っているので、必要かと思いおいております。

2020-11-16 04:55 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +                self.dismiss(animated: true, completion: nil)
その危険性もあるんですね。。。あまり使わない方が好ましい、ということは書き直す方がよいですかね？

いえ！入力画面に戻ります！

2020-11-16 04:58 UTC, ryudrag commented on MyTodo.xcodeproj/project.pbxproj
> +				0F3BF6AD2553FB75007628D4 /* ContentViewCell.swift */,
良くする意図があるんだったらまだこのままでもいいけど、
悪くなってるのに戻さないとダメなんでしょうかは無しだね。

2020-11-16 04:58 UTC, ryudrag commented on MyTodo.xcodeproj/project.pbxproj
> +				0F3BF6AD2553FB75007628D4 /* ContentViewCell.swift */,
D&Dで移動できる。

2020-11-16 04:59 UTC, ochibi1 commented on MyTodo.xcodeproj/project.pbxproj
> +				0F3BF6AD2553FB75007628D4 /* ContentViewCell.swift */,
悪くなっている＝意図していない変更がある→戻す　という理解で間違ってないでしょうか？

2020-11-16 05:01 UTC, ryudrag commented
あーあと、全体として差分確認してる？
チェック（”再”含む）をお願いする前に、

- 余分なコミットが含まれていないか
- 意図しない差分が含まれないか

を確認するのは基本ね。

2020-11-16 05:03 UTC, ryudrag commented on MyTodo.xcodeproj/project.pbxproj
> +				0F3BF6AD2553FB75007628D4 /* ContentViewCell.swift */,
そうそう。

2020-11-16 05:04 UTC, ochibi1 commented on MyTodo.xcodeproj/project.pbxproj
> +				0F3BF6AD2553FB75007628D4 /* ContentViewCell.swift */,
理解です！有難うございます！

2020-11-16 05:05 UTC, ochibi1 commented
基本的な部分、徹底できていなかったです。ご指摘有難うございます。

Xcodeのcommit, pushの部分で見える差分で確認する、ので大丈夫なんでしょうか？

2020-11-16 05:22 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +                self.dismiss(animated: true, completion: nil)
動作確認した？

2020-11-16 05:23 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +                self.dismiss(animated: true, completion: nil)
動作確認行っています。
OKを押した後、入力画面に戻るのを確認済みです。

2020-11-16 05:23 UTC, ryudrag commented
差分確認はこのPRでいいよ（PR作ったあとの場合）。PR作るときは、作成画面の下のほうに出てるからそこで確認。

2020-11-16 05:27 UTC, ryudrag commented
LayoutConstraintsに関するワーニングが出てるから直しておいて。
デバッグコンソールのとこに。

2020-11-16 05:30 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +                self.dismiss(animated: true, completion: nil)
おそらく、dismissの中で破棄できるかどうかの判断をやってくれているから問題ないんだろうけど、
`self.dismiss(animated: true, completion: nil)` は `自分自身を破棄しなさい` ね。
ここでいうとItemAddViewControllerクラス。

2020-11-16 05:34 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +                self.dismiss(animated: true, completion: nil)
入力欄が空白の状態で保存ボタンをクリックされた時に呼び出される部分だから、空白のselfがdismissされても大丈夫なのでは、と考えていました。

2020-11-16 05:35 UTC, ochibi1 commented
pushした後に、PRで差分確認。不要な差分がない状態でチェックを依頼、という流れで行うということですね。理解しました。有難うございます！

2020-11-16 05:38 UTC, ochibi1 commented
これ、ワーニングだったのですね、、コンソール部分確認したので、やってみます。ご指摘有難うございます。

2020-11-16 05:51 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +                self.dismiss(animated: true, completion: nil)
で、あれば、selfの認識が間違っているので、この時点でのselfが何なのかを確認してみて。

2020-11-16 05:53 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +                self.dismiss(animated: true, completion: nil)
確認します！ご指摘有難うございます！

2020-11-16 14:26 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +                print("OK")
55行目のprint、もしまだ修正がある場合に使うため、分かりやすい位置に残しておきたかったので、残してあります。

2020-11-16 22:09 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +                print("OK")
オッケーだから消しといてー。

2020-11-16 22:10 UTC, ryudrag reviewed
printを消しといて。

2020-11-17 00:53 UTC, ryudrag commented on MyTodo/ItemAddViewController.swift
> +            }))
ここのhandlerの引数はnilでいけるんじゃない？
下の保存できなかったアラートも修正ね。

2020-11-17 01:15 UTC, ochibi1 commented on MyTodo/ItemAddViewController.swift
> +            }))
変更しました！ご確認よろしくお願いいたします。

2020-11-17 01:22 UTC, ryudrag approved these changes

2020-11-17 01:29 UTC, merged